import { notFound } from "next/navigation";
import { connectDB } from "@/lib/mongodb";
import Workspace from "@/lib/models/Workspace";
import User from "@/lib/models/User";
import { PreviewClient } from "@/components/PreviewClient";
import type { FileData } from "@/types/workspace";

interface PreviewPageProps {
  params: Promise<{ subdomain: string }>;
}

export default async function PreviewPage({ params }: PreviewPageProps) {
  const { subdomain } = await params;

  if (!subdomain) {
    notFound();
  }

  await connectDB();

  // Find the workspace that matches this subdomain
  const workspace = await Workspace.findOne({ subdomain }).lean();

  if (!workspace || !workspace.fileData) {
    notFound();
  }

  const fileData = workspace.fileData as FileData;

  // Fetch the user to check their plan
  const user = await User.findById(workspace.userId).select("plan").lean();
  const isProUser = user?.plan === "pro";

  return (
    <main className="relative h-screen w-screen bg-white">
      <PreviewClient 
        fileData={fileData} 
        title={workspace.title || "Live Preview"} 
        isProUser={isProUser}
      />
    </main>
  );
}

// Generate dynamic metadata for the preview site
export async function generateMetadata({ params }: PreviewPageProps) {
  const { subdomain } = await params;
  await connectDB();
  const workspace = await Workspace.findOne({ subdomain }).lean();

  return {
    title: workspace?.title || "Generated Website",
    description: "A website generated by Crevo AI.",
  };
}
